name: Python Tests

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FIO: "Старков Артем Алексеевич"
      GROUP: "М3112"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display Info
        run: |
          echo "ФИО: ${{ env.FIO }}"
          echo "Номер группы: ${{ env.GROUP }}"
          echo "Ник на Github: ${{ github.actor }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests

      - name: Lint code
        run: |
          pip install flake8
          flake8 .
